version: "3.2"
services:
    myapp:
        tty: true
        image: docker.io/bitnami/laravel:8
        environment:
            - DB_HOST=db
            - DB_USERNAME=cleyton
            - DB_DATABASE=mydb
            - DB_PASSWORD=123
        depends_on:
            - db
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        privileged: true # Privileged mode could be required to run this container under Windows

    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: cleyton
            MYSQL_PASSWORD: 123

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8088:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
